<?php

/**
 * Generated By:
 * DCA Module Generator for Contao Open Source CMS
 *
 * Copyright (C) 2016 Andrew Stevens
 *
 * @package    DCA Generator
 * @link       http://andrewstevens.consulting
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */


 
/**
 * Add a palette to tl_module
 */
$GLOBALS['TL_DCA']['tl_module']['palettes']['peerless_dealers_list'] 		= '{title_legend},name,headline,type;{redirect_legend},jumpTo;{template_legend:hide},customTpl,peerless_dealers_customItemTpl;{expert_legend:hide},guests,cssID,space';
$GLOBALS['TL_DCA']['tl_module']['palettes']['peerless_dealers_reader']		= '{title_legend},name,headline,type;{template_legend:hide},peerless_dealers_customItemTpl;{expert_legend:hide},guests,cssID,space';

$GLOBALS['TL_DCA']['tl_module']['fields']['peerless_dealers_customItemTpl'] = array
(
	'label'                   => &$GLOBALS['TL_LANG']['tl_module']['customItemTpl'],
	'exclude'                 => true,
	'inputType'               => 'select',
	'options_callback'        => array('tl_module', 'getModuleTemplates'),
	'eval'                    => array('includeBlankOption'=>true, 'chosen'=>true, 'tl_class'=>'w50'),
	'sql'                     => "varchar(64) NOT NULL default ''"
);

/**
 * Provide miscellaneous methods that are used by the auto generated data configuration array.
 *
 */
class tl_module_peerless_dealers extends Backend
{
	/**
	 * Return all item templates as array
	 *
	 * @return array
	 */
	public function getItemTemplates()
	{
		return $this->getTemplateGroup('item_peerless_dealers');
	}

}