<?php
 
/**
 * Generated By:
 * DCA Module Generator for Contao Open Source CMS
 *
 * Copyright (C) 2016 Andrew Stevens
 *
 * @package    DCA Generator
 * @link       http://andrewstevens.consulting
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */



/**
 * Table tl_peerless_dealers
 */
$GLOBALS['TL_DCA']['tl_peerless_dealers'] = array
(
 
    // Config
    'config' => array
    (
        'dataContainer'               => 'Table',
        'enableVersioning'            => true,
        'sql' => array
        (
            'keys' => array
            (
                'id' => 'primary',
                'alias' => 'index'
            )
        )
    ),
 
    // List
    'list' => array
    (
        'sorting' => array
        (
            'mode'                    => 1,
            'fields'                  => array('name'),
            'flag'                    => 1,
            'panelLayout'             => 'filter;search,limit'
        ),
        'label' => array
        (
            'fields'                  => array('name', 'address'),
            'format'                  => '%s (%s)'
        ),
        'global_operations' => array
        (
            'all' => array
            (
                'label'               => &$GLOBALS['TL_LANG']['MSC']['all'],
                'href'                => 'act=select',
                'class'               => 'header_edit_all',
                'attributes'          => 'onclick="Backend.getScrollOffset()" accesskey="e"'
            )
        ),
        'operations' => array
        (
            'edit' => array
            (
                'label'               => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['edit'],
                'href'                => 'act=edit',
                'icon'                => 'edit.gif'
            ),
            'copy' => array
            (
                'label'               => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['copy'],
                'href'                => 'act=copy',
                'icon'                => 'copy.gif'
            ),
            'delete' => array
            (
                'label'               => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['delete'],
                'href'                => 'act=delete',
                'icon'                => 'delete.gif',
                'attributes'          => 'onclick="if(!confirm(\'' . $GLOBALS['TL_LANG']['MSC']['deleteConfirm'] . '\'))return false;Backend.getScrollOffset()"'
            ),
            'toggle' => array
			(
				'label'               => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['toggle'],
				'icon'                => 'visible.gif',
				'attributes'          => 'onclick="Backend.getScrollOffset();return AjaxRequest.toggleVisibility(this,%s)"',
				'button_callback'     => array('tl_peerless_dealers', 'toggleIcon')
			),
            'show' => array
            (
                'label'               => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['show'],
                'href'                => 'act=show',
                'icon'                => 'show.gif'
            )
        )
    ),
 
    // Palettes
    'palettes' => array
    (
        'default'                     => '{generated_legend},alias,name,address,phone,phone_2,fax,email,url,description,latitude,longitude;{publish_legend},published;'
    ),
 
    // Fields
    'fields' => array
    (
	
        'id' => array
        (
            'sql'                     => "int(10) unsigned NOT NULL auto_increment"
        ),
        'tstamp' => array
        (
            'sql'                     => "int(10) unsigned NOT NULL default '0'"
        ),
		'sorting' => array
		(
			'sql'                     => "int(10) unsigned NOT NULL default '0'"
		),
		'alias' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['alias'],
			'exclude'                 => true,
			'inputType'               => 'text',
			'search'                  => true,
			'eval'                    => array('unique'=>true, 'rgxp'=>'alias', 'doNotCopy'=>true, 'maxlength'=>128, 'tl_class'=>'w50'),
			'save_callback' => array
			(
				array('tl_peerless_dealers', 'generateAlias')
			),
			'sql'                     => "varchar(128) COLLATE utf8_bin NOT NULL default ''"

		),
		'name' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['name'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'address' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['address'],
			'inputType'               => 'text',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'phone' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['phone'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'phone_2' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['phone_2'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'fax' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['fax'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'email' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['email'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'url' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['url'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'description' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['description'],
			'inputType'               => 'textarea',
			'eval'                    => array('rows'=>4, 'cols'=>40),
			'sql'                     => "mediumtext NULL"
		),
		'latitude' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['latitude'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'longitude' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['longitude'],
			'inputType'               => 'text',
			'default'				  => '',
			'eval'                    => array(),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
		'published' => array
		(
			'exclude'                 => true,
			'label'                   => &$GLOBALS['TL_LANG']['tl_peerless_dealers']['published'],
			'inputType'               => 'checkbox',
			'eval'                    => array('submitOnChange'=>true, 'doNotCopy'=>true),
			'sql'                     => "char(1) NOT NULL default ''"
		)		
    )
);

/**
 * Class tl_peerless_dealers
 */
class tl_peerless_dealers extends Backend
{
	/**
	 * Auto-generate an article alias if it has not been set yet
	 * @param mixed
	 * @param \DataContainer
	 * @return string
	 * @throws \Exception
	 */
	public function generateAlias($varValue, DataContainer $dc)
	{
		$autoAlias = false;
		$strFieldToAlias = 'name';

		// Generate an alias if there is none
		if ($varValue == '')
		{
			$autoAlias = true;
			if ($strFieldToAlias != '') {
				$varValue = standardize(StringUtil::restoreBasicEntities($dc->activeRecord->{$strFieldToAlias}));
			} else {
				$varValue = standardize(StringUtil::restoreBasicEntities(md5(uniqid() .$dc->activeRecord->id)));
			}
		}

		$objAlias = $this->Database->prepare("SELECT id FROM tl_peerless_dealers WHERE id=? OR alias=?")
								   ->execute($dc->id, $varValue);

		// Check whether the page alias exists
		if ($objAlias->numRows > 1)
		{
			if (!$autoAlias)
			{
				throw new Exception(sprintf($GLOBALS['TL_LANG']['ERR']['aliasExists'], $varValue));
			}

			$varValue .= '-' . $dc->id;
		}

		return $varValue;
	}
	

	/**
	 * Return the "toggle visibility" button
	 * @param array
	 * @param string
	 * @param string
	 * @param string
	 * @param string
	 * @param string
	 * @return string
	 */
	public function toggleIcon($row, $href, $label, $title, $icon, $attributes)
	{
		if (strlen(Input::get('tid')))
		{
			$this->toggleVisibility(Input::get('tid'), (Input::get('state') == 1), (@func_get_arg(12) ?: null));
			$this->redirect($this->getReferer());
		}

		$href .= '&amp;tid='.$row['id'].'&amp;state='.($row['published'] ? '' : 1);

		if (!$row['published'])
		{
			$icon = 'invisible.gif';
		}

		return '<a href="'.$this->addToUrl($href).'" title="'.specialchars($title).'"'.$attributes.'>'.Image::getHtml($icon, $label).'</a> ';
	}	
	
	
	/**
	 * Disable/enable a user group
	 * @param integer
	 * @param boolean
	 * @param \DataContainer
	 */
	public function toggleVisibility($intId, $blnVisible, DataContainer $dc=null)
	{
		$objVersions = new Versions('tl_peerless_dealers', $intId);
		$objVersions->initialize();

		// Trigger the save_callback
		if (is_array($GLOBALS['TL_DCA']['tl_peerless_dealers']['fields']['published']['save_callback']))
		{
			foreach ($GLOBALS['TL_DCA']['tl_peerless_dealers']['fields']['published']['save_callback'] as $callback)
			{
				if (is_array($callback))
				{
					$this->import($callback[0]);
					$blnVisible = $this->$callback[0]->$callback[1]($blnVisible, ($dc ?: $this));
				}
				elseif (is_callable($callback))
				{
					$blnVisible = $callback($blnVisible, ($dc ?: $this));
				}
			}
		}

		// Update the database
		$this->Database->prepare("UPDATE tl_peerless_dealers SET tstamp=". time() .", published='" . ($blnVisible ? 1 : '') . "' WHERE id=?")
					   ->execute($intId);

		$objVersions->create();
		$this->log('A new version of record "tl_peerless_dealers.id='.$intId.'" has been created'.$this->getParentEntries('tl_peerless_dealers', $intId), __METHOD__, TL_GENERAL);
	}		
		
}
