<?php

/**
 * Generated By:
 * DCA Module Generator for Contao Open Source CMS
 *
 * Copyright (C) 2016 Andrew Stevens
 *
 * @package    DCA Generator
 * @link       http://andrewstevens.consulting
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */



/**
 * Register the classes
 */
ClassLoader::addClasses(array
(
    'Contao\ModulePeerlessDealersList' => 'system/modules/peerless_dealers/library/Contao/ModulePeerlessDealersList.php',
	'Contao\ModulePeerlessDealersReader' => 'system/modules/peerless_dealers/library/Contao/ModulePeerlessDealersReader.php',
));

/**
 * Register the templates
 */
TemplateLoader::addFiles(array
(
    'mod_peerless_dealers_list' => 'system/modules/peerless_dealers/templates/modules',
	'item_peerless_dealers_generated' => 'system/modules/peerless_dealers/templates/items',
));
