<?php

/**
 * Generated By:
 * DCA Module Generator for Contao Open Source CMS
 *
 * Copyright (C) 2016 Andrew Stevens
 *
 * @package    DCA Generator
 * @link       http://andrewstevens.consulting
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */



/**
* Back end modules
*/
if (!array_key_exists('peerless', $GLOBALS['BE_MOD'])) {
	$GLOBALS['BE_MOD'] = array_merge(array('peerless' => array()), $GLOBALS['BE_MOD']);
}
$GLOBALS['BE_MOD']['peerless']['peerless_dealers'] = array(
	'tables' => array('tl_peerless_dealers'),
	'icon'   => 'system/modules/peerless_dealers/assets/icons/dealer.png'
);

/**
* Front end modules
*/
$GLOBALS['FE_MOD']['peerless']['peerless_dealers_list'] 	= 'ModulePeerlessDealersList';
$GLOBALS['FE_MOD']['peerless']['peerless_dealers_reader'] 	= 'ModulePeerlessDealersReader';