<?php
 
/**
 * Generated By:
 * DCA Module Generator for Contao Open Source CMS
 *
 * Copyright (C) 2016 Andrew Stevens
 *
 * @package    DCA Generator
 * @link       http://andrewstevens.consulting
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */

 
 
/**
 * Front end modules
 */
$GLOBALS['TL_LANG']['FMD']['peerless']					= array('Peerless', 'Peerlesss Modules.');
$GLOBALS['TL_LANG']['FMD']['peerless_dealers_list'] 	= array('Dealers List', 'Peerless Dealers list module.');
$GLOBALS['TL_LANG']['FMD']['peerless_dealers_reader'] 	= array('Dealers Reader', 'Peerless Dealers reader module.');

/**
 * Back end modules
 */
$GLOBALS['TL_LANG']['MOD']['peerless'] 					= array('Peerless', 'Modules generated by the DCA Generator Module');
$GLOBALS['TL_LANG']['MOD']['peerless_dealers'] 			= array('Dealers', 'Configure Peerless Dealers');

