<?php
 
/**
 * Generated By:
 * DCA Module Generator for Contao Open Source CMS
 *
 * Copyright (C) 2016 Andrew Stevens
 *
 * @package    DCA Generator
 * @link       http://andrewstevens.consulting
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */

 
 
/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_module']['customItemTpl'] 	= array('Custom item template', 'Here you can overwrite the default item template.');
