<?php
 
/**
 * Generated By:
 * DCA Module Generator for Contao Open Source CMS
 *
 * Copyright (C) 2016 Andrew Stevens
 *
 * @package    DCA Generator
 * @link       http://andrewstevens.consulting
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */

 

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_peerless_dealers']['generated_legend'] 	= 'DCA Generator Fields';
$GLOBALS['TL_LANG']['tl_peerless_dealers']['publish_legend'] 		= 'Publish';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_peerless_dealers']['alias'] 	= array('Alias', 'Please enter an alias.');
$GLOBALS['TL_LANG']['tl_peerless_dealers']['name'] 	= array('Name', 'Name');$GLOBALS['TL_LANG']['tl_peerless_dealers']['address'] 	= array('Full Address', 'Full Address');$GLOBALS['TL_LANG']['tl_peerless_dealers']['phone'] 	= array('Phone', 'Phone');$GLOBALS['TL_LANG']['tl_peerless_dealers']['phone_2'] 	= array('Phone 2', 'Phone 2');$GLOBALS['TL_LANG']['tl_peerless_dealers']['fax'] 	= array('Fax', 'Fax');$GLOBALS['TL_LANG']['tl_peerless_dealers']['email'] 	= array('Email', 'Email');$GLOBALS['TL_LANG']['tl_peerless_dealers']['url'] 	= array('Website', 'Website');$GLOBALS['TL_LANG']['tl_peerless_dealers']['description'] 	= array('Description', 'Description');$GLOBALS['TL_LANG']['tl_peerless_dealers']['latitude'] 	= array('Latitude Coordinates', 'Latitude Coordinates');$GLOBALS['TL_LANG']['tl_peerless_dealers']['longitude'] 	= array('Longitude Coordinates', 'Longitude Coordinates');
$GLOBALS['TL_LANG']['tl_peerless_dealers']['published'] 	= array('Published', 'Show this record on the front end.');
 
 /**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_peerless_dealers']['new']    = array('New record', 'Add a new record');
$GLOBALS['TL_LANG']['tl_peerless_dealers']['show']   = array('Record details', 'Show the details of record ID %s');
$GLOBALS['TL_LANG']['tl_peerless_dealers']['edit']   = array('Edit record', 'Edit record ID %s');
$GLOBALS['TL_LANG']['tl_peerless_dealers']['copy']   = array('Copy record', 'Copy record ID %s');
$GLOBALS['TL_LANG']['tl_peerless_dealers']['delete'] = array('Delete record', 'Delete record ID %s');
$GLOBALS['TL_LANG']['tl_peerless_dealers']['toggle'] = array('Toggle record', 'Toggle record ID %s');
